Server/Areas/Administration/Pages/Shop/Orders/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Order;
using UserManagement.Application.Contracts.User;

namespace Server.Areas.Administration.Pages.Shop.Orders
{
    public class IndexModel : PageModel
    {
        private readonly IOrderApplication _orderApplication;
        private readonly IUserApplication _userApplication;

        public IndexModel(IOrderApplication orderApplication,IUserApplication userApplication)
        {
            _orderApplication = orderApplication;
            _userApplication = userApplication;
        }

        public SelectList UsersSelectList { get; set; }
        public Tuple<List<OrderViewModel>,int,int,int> OrderVMs { get; set; }

        public OrderSearchModel SearchModel { get; set; }
        public void OnGet(OrderSearchModel searchModel)
        {
            ViewData["Take"] = searchModel.Take;
            UsersSelectList = new SelectList(_userApplication.GetUsersForSelect(), "Value", "Text");
            OrderVMs = _orderApplication.GetOrders(searchModel);
        }

        public IActionResult OnGetShowOrderItems(long orderId)
        {
            var orderItems = _orderApplication.GetOrderItems(orderId);
            return Partial("./OrderItems",orderItems);
        }

        public IActionResult OnGetConfirmOrder(long orderId)
        {
            return Partial("./Confirm",orderId);
        }

        public IActionResult OnPostConfirmOrder(long orderId)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _orderApplication.ConfirmOrderForSent(orderId);
            return new JsonResult(result);
        }

        public IActionResult OnGetCancelOrder(long orderId)
        {
            return Partial("./Cancel", orderId);
        }

        public IActionResult OnPostCancelOrder(long orderId)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _orderApplication.CancelOrder(orderId);
            return new JsonResult(result);
        }
    }
}

Server/Areas/Administration/Pages/Shop/ProductBrands/Index.cshtml.cs
using System.Collections.Immutable;
using _01_Framework.Resources;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductBrand;

namespace Server.Areas.Administration.Pages.Shop.ProductBrands
{
    public class IndexModel : PageModel
    {
        private readonly IProductBrandApplication _productBrandApplication;

        public IndexModel(IProductBrandApplication productBrandApplication)
        {
            _productBrandApplication = productBrandApplication;
        }

        public Tuple<List<ProductBrandViewModel>,int,int,int> ProductBrandVms { get; set; }
        public void OnGet(int pageId=1,string title="",int take=20)
        {
            if (take % 20 != 0)
                take = 20;
            ViewData["Take"] = take;
            ProductBrandVms = _productBrandApplication.GetProductBrands(pageId,title,take);
        }

        public IActionResult OnGetCreate()
        {
            return Partial("./Create");
        }

        public IActionResult OnPostCreate(CreateBrandCommand command)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var result = _productBrandApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long brandId)
        {
            var brand = _productBrandApplication.GetBrandForEdit(brandId);
            return Partial("./Edit", brand);
        }

        public IActionResult OnPostEdit(EditBrandCommand command)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productBrandApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetDelete(long brandId)
        {
            if (_productBrandApplication.IsProductsHaveBrand(brandId))
            {
                return BadRequest(ErrorMessages.DeleteBrandErrorMessage);
            }
            var brand= _productBrandApplication.GetBrandForDelete(brandId);
            return Partial("./Delete",brand);
        }

        public IActionResult OnPostDelete(DeleteBrandCommand command)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productBrandApplication.Delete(command);
            return new JsonResult(result);
        }
    }
}

Server/Areas/Administration/Pages/Shop/ProductColors/Index.cshtml.cs
using _01_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductColor;
using ShopManagement.Infrastructure.Configuration.Permissions;

namespace Server.Areas.Administration.Pages.Shop.ProductColors
{
    public class IndexModel : PageModel
    {
        private readonly IProductColorApplication _productColorApplication;

        public IndexModel(IProductColorApplication productColorApplication)
        {
            _productColorApplication = productColorApplication;
        }

        [NeedsPermission(ProductPermissions.CreateProductColor)]
        public IActionResult OnGetCreate(long productId)
        {
            return Partial("./Create",new CreateColorCommand(){ProductId = productId});
        }

        [NeedsPermission(ProductPermissions.CreateProductColor)]
        public IActionResult OnPostCreate(CreateColorCommand command)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productColorApplication.Create(command);
            return new JsonResult(result);
        }

        [NeedsPermission(ProductPermissions.DeleteProductColor)]
        public IActionResult OnPostDelete(long colorId)
        {
            if (!ModelState.IsValid)
                return Redirect("/Administration/Shop/Products");
            _productColorApplication.Delete(colorId);
            return Redirect("/Administration/Shop/Products");
        }
    }
}

Server/Areas/Administration/Pages/Shop/ProductGroups/GroupDetails/Index.cshtml.cs
using _01_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductGroup;
using ShopManagement.Infrastructure.Configuration.Permissions;

namespace Server.Areas.Administration.Pages.Shop.ProductGroups.GroupDetails
{
    public class IndexModel : PageModel
    {
        private readonly IProductGroupApplication _productGroupApplication;

        public IndexModel(IProductGroupApplication productGroupApplication)
        {
            _productGroupApplication = productGroupApplication;
        }

        public List<GroupDetailViewModel> GroupDetailVms { get; set; }
        [BindProperty]
        public CreateGroupDetailCommand command { get; set; }

        [NeedsPermission(ProductGroupPermissions.GroupDetailsList)]
        public void OnGet(long groupId)
        {
            command = new CreateGroupDetailCommand()
            {
                GroupId = groupId
            };
            GroupDetailVms = _productGroupApplication.GetDetailsOfGroup(groupId);
        }

        [NeedsPermission(ProductGroupPermissions.CreateGroupDetail)]
        public IActionResult OnPostCreate()
        {
            ModelState.Remove("DetailId");
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productGroupApplication.CreateGroupDetail(command);
            return new JsonResult(result);
        }

        [NeedsPermission(ProductGroupPermissions.EditGroupDetail)]
        public IActionResult OnPostEdit()
        {
            if (!ModelState.IsValid || command.DetailId==null)
                return BadRequest();
            var result = _productGroupApplication.EditGroupDetail(command);
            return new JsonResult(result);
        }
    }
}

Server/Areas/Administration/Pages/Shop/ProductGroups/Index.cshtml.cs
using _01_Framework.Infrastructure;
using _01_Framework.Resources;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductGroup;
using ShopManagement.Infrastructure.Configuration.Permissions;

namespace Server.Areas.Administration.Pages.Shop.ProductGroups
{
    public class IndexModel : PageModel
    {
        public IndexModel(IProductGroupApplication productGroupApplication,IProductApplication productApplication)
        {
            _productGroupApplication = productGroupApplication;
            _productApplication = productApplication;
        }
        private readonly IProductGroupApplication _productGroupApplication;
        private readonly IProductApplication _productApplication;
        public Tuple<List<ProductGroupViewModel>,int,int,int> ProductGroupVm { get; set; }

        [NeedsPermission(ProductGroupPermissions.PoductGroupsList)]
        public void OnGet(int pageId=1,string title="",int take=10)
        {
            if (take % 10 != 0)
                take = 10;
            ViewData["Take"] = take;
            ProductGroupVm = _productGroupApplication.GetProductGroupsForShow(pageId, title, take);
        }

        [NeedsPermission(ProductGroupPermissions.CreateGroup)]
        public IActionResult OnGetCreate(long? parentId)
        {
            var createGroupCommand = new CreateGroupCommand()
            {
                ParentId = parentId
            };
            return Partial("./Create",createGroupCommand);
        }

        [NeedsPermission(ProductGroupPermissions.CreateGroup)]
        public IActionResult OnPostCreate(CreateGroupCommand command)
        {
            ModelState.Remove("ParentId");
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productGroupApplication.CreateGroup(command);
            return new JsonResult(result);
        }

        [NeedsPermission(ProductGroupPermissions.EditGroup)]
        public IActionResult OnGetEdit(long groupId)
        {
            var group = _productGroupApplication.GetGroupForEdit(groupId);
            return Partial("./Edit",group);
        }

        [NeedsPermission(ProductGroupPermissions.EditGroup)]
        public IActionResult OnPostEdit(EditGroupCommand command)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productGroupApplication.EditGroup(command);
            return new JsonResult(result);
        }

        [NeedsPermission(ProductGroupPermissions.DeleteGroup)]
        public IActionResult OnGetDelete(long groupId)
        {
            if (_productApplication.IsExistProductByGroup(groupId))
            {
                return BadRequest(ErrorMessages.DeleteGroupErrorMessage);
            }

            var group = _productGroupApplication.GetGroupForDelete(groupId);
            return Partial("./Delete",group);
        }

        [NeedsPermission(ProductGroupPermissions.DeleteGroup)]
        public IActionResult OnPostDelete(long groupId)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productGroupApplication.DeleteGroup(groupId);
            return new JsonResult(result);
        }
    }
}

Server/Areas/Administration/Pages/Shop/ProductImages/Index.cshtml.cs
using _01_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductImage;
using ShopManagement.Infrastructure.Configuration.Permissions;

namespace Server.Areas.Administration.Pages.Shop.ProductImages
{
    public class IndexModel : PageModel
    {
        private readonly IProductImageApplication _productImageApplication;

        public IndexModel(IProductImageApplication productImageApplication)
        {
            _productImageApplication = productImageApplication;
        }
        public List<ProductImageViewModel> ProductImages { get; set; }

        [NeedsPermission(ProductPermissions.ProductImagesList)]
        public void OnGet(long productId)
        {
            ProductImages = _productImageApplication.GetProductImages(productId);
        }
        [NeedsPermission(ProductPermissions.CreateProductImage)]
        public IActionResult OnGetCreate(long productId)
        {
            return Partial("./Create",new CreateImageCommand(){ProductId = productId});
        }

        [NeedsPermission(ProductPermissions.CreateProductImage)]
        public IActionResult OnPostCreate(CreateImageCommand command)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productImageApplication.Create(command);
            return new JsonResult(result);
        }

        [NeedsPermission(ProductPermissions.DeleteProductImage)]
        public IActionResult OnPostDelete(long imageId)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productImageApplication.Delete(imageId);
            return Redirect("/Administration/Shop/Products");
        }
    }
}

Server/Areas/Administration/Pages/Shop/Products/ProductDetails/Index.cshtml.cs
using _01_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Infrastructure.Configuration.Permissions;

namespace Server.Areas.Administration.Pages.Shop.Products.ProductDetails
{
    public class IndexModel : PageModel
    {
        private readonly IProductApplication _productApplication;

        public IndexModel(IProductApplication productApplication)
        {
            _productApplication = productApplication;
        }

        public List<ProductDetailViewModel> ProductDetailVms { get; set; }

        [NeedsPermission(ProductPermissions.ConfirmProductDetails)]
        public void OnGet(long productId)
        {
            @ViewData["ProductId"] = productId;
            ProductDetailVms = _productApplication.GetProductDetails(productId);
        }

        [NeedsPermission(ProductPermissions.ConfirmProductDetails)]
        public IActionResult OnPost(long productId,Dictionary<int,string> details)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productApplication.ConfirmProductDetails(productId, details);
            return new JsonResult(result);
        }
    }
}

Server/Pages/UserPanel/Orders.cshtml.cs
using DigikalaQuery.Contracts.Order;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Server.Pages.UserPanel
{
    [Authorize]
    public class OrdersModel : PageModel
    {
        private readonly IOrderQuery _orderQuery;

        public OrdersModel(IOrderQuery orderQuery)
        {
            _orderQuery = orderQuery;
        }

        public Tuple<List<OrderQueryModel>,List<OrderQueryModel>,List<OrderQueryModel>,List<OrderQueryModel>> OrderQueryModels { get; set; }
        public void OnGet()
        {
            OrderQueryModels = _orderQuery.GetUserOrders();
        }
    }
}

Server/Areas/Administration/Pages/Shop/Orders/Cancel.cshtml
@model long
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">@DataDictionaries.ConfirmOrder</h4>
</div>
<form asp-page="./Index"
      asp-page-handler="CancelOrder"
      data-ajax="true"
      data-action="Refresh"
      enctype="multipart/form-data"
      method="post">
    <div class="modal-body">
        @ConfirmationMessages.CancelOrderMessage
    </div>
    <input type="hidden" name="orderId" value="@Model" />
    <div class="modal-footer">
        <button type="submit" class="btn btn-danger waves-effect waves-light">@ButtonCaptions.CancelOrder</button>
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">@ButtonCaptions.Cancel</button>
    </div>

</form>

Server/Areas/Administration/Pages/Shop/Orders/Confirm.cshtml
@model long
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">@DataDictionaries.ConfirmOrder</h4>
</div>
<form asp-page="./Index"
      asp-page-handler="ConfirmOrder"
      data-ajax="true"
      data-action="Refresh"
      enctype="multipart/form-data"
      method="post">
    <div class="modal-body">
        @ConfirmationMessages.ConfirmOrderMessage
    </div>
    <input type="hidden" name="orderId" value="@Model" />
    <div class="modal-footer">
        <button type="submit" class="btn btn-info waves-effect waves-light">@ButtonCaptions.Confirm</button>
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">@ButtonCaptions.Cancel</button>
    </div>

</form>

Server/Areas/Administration/Pages/Shop/Orders/Index.cshtml
@page "{handler?}"
@using ShopManagement.Infrastructure.EfCore.Repositories
@model Server.Areas.Administration.Pages.Shop.Orders.IndexModel
@{
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">@DataDictionaries.OrdersList</h3>
            </div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                            <form method="get">
                                <div class="row">
                                    <div class="col-md-2">
                                        <div id="datatable_filter" class="dataTables_filter">
                                            <label style="display: block">@DataDictionaries.SelectUserMessage</label>
                                            <select asp-for="SearchModel.UserId" asp-items="Model.UsersSelectList" class="select2 select2-offscreen" tabindex="-1" title="">
                                                <option value="">&nbsp;</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div id="datatable_filter" class="dataTables_filter">
                                            <label style="display: block">@DataDictionaries.TrackingId</label>
                                            <input asp-for="SearchModel.TrackingNumber" type="search" class="form-control input-sm" aria-controls="datatable">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div id="datatable_filter" class="dataTables_filter">
                                            <label style="display: block">@DataDictionaries.OrderStatus</label>
                                            <select asp-for="SearchModel.Status" class="form-control">
                                                <option value="0">&nbsp;</option>
                                                <option value="1">@DataDictionaries.NotPaid</option>
                                                <option value="2">@DataDictionaries.IsWaiting</option>
                                                <option value="3">@DataDictionaries.Sent</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="dataTables_length" id="datatable_length">
                                            <label style="display:block">@DataDictionaries.Show</label>
                                            <select name="take" aria-controls="datatable" class="form-control input-sm">
                                                @for (var i = 1; i <= 4; i++)
                                                {
                                                    int x = 10;
                                                    if (i * x == (int)ViewData["Take"])
                                                    {
                                                        <option value="@(i * x)" selected>@(i * x)</option>
                                                    }
                                                    else
                                                    {
                                                        <option value="@(i * x)">@(i * x)</option>
                                                    }
                                                }
                                            </select>
                                            @DataDictionaries.Record
                                        </div>
                                    </div>
                                    <div class="col-md-3  m-t-10">
                                        <div id="datatable_filter" class="dataTables_filter">
                                            <input type="submit" class="btn btn-primary" value="@ButtonCaptions.Search" />
                                            <a href="/Administration/Shop/Orders" class="btn btn-warning">@ButtonCaptions.Clear</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <div class="row m-t-10">
                                <div class="col-sm-12">
                                    <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
                                        <thead>
                                            <tr role="row">
                                                <th>@DataDictionaries.OrderUser</th>
                                                <th>@DataDictionaries.Address</th>
                                                <th>@(DataDictionaries.TotalOrderPrice+$"({DataDictionaries.Toman})")</th>
                                                <th>@(DataDictionaries.DiscountPrice+$"({DataDictionaries.Toman})")</th>
                                                <th>@(DataDictionaries.PaidPrice+$"({DataDictionaries.Toman})")</th>
                                                <th>@DataDictionaries.TrackingId</th>
                                                <th>@DataDictionaries.CreationDate</th>
                                                <th>@DataDictionaries.OrderStatus</th>
                                                <th>@DataDictionaries.Operations</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var order in Model.OrderVMs.Item1)
                                            {
                                                <tr role="row">
                                                    <td>@order.UserName</td>
                                                    <td>@order.Address</td>
                                                    <td>@order.OrderSum.ToString("#,0")</td>
                                                    <td>@order.OrderDiscount.ToString("#,0")</td>
                                                    <td>@order.PaidPrice.ToString("#,0")</td>
                                                    <td>@order.TrackingNumber</td>
                                                    <td>@order.CreationDate</td>
                                                    <td>
                                                        @if (order.Status == OrderStatuses.NotPaid)
                                                        {
                                                            <p class="text-secondary">@DataDictionaries.NotPaid</p>
                                                        }
                                                        else if (order.Status == OrderStatuses.IsWaiting)
                                                        {
                                                            <p class="text-warning">@DataDictionaries.IsWaiting</p>
                                                        }
                                                        else if (order.Status == OrderStatuses.OrderSent)
                                                        {
                                                            <p class="text-success">@DataDictionaries.Sent</p>
                                                        }
                                                        else
                                                        {
                                                            <p class="text-danger">@DataDictionaries.Cancelled</p>
                                                        }
                                                    </td>
                                                    <td>
                                                        <a onclick="GetOrderItems(@order.OrderId)" class="btn btn-primary btn-block largeModal">@ButtonCaptions.OrderDetails</a>
                                                        @if (order.Status != OrderStatuses.OrderSent)
                                                        {
                                                            <a onclick="ConfirmOrder(@order.OrderId)" class="btn btn-success btn-block smallModal">@ButtonCaptions.Confirm</a>
                                                            @if (order.Status != OrderStatuses.Cancelled)
                                                            {
                                                                <a onclick="CancelOrder(@order.OrderId)" class="btn btn-danger btn-block smallModal">@ButtonCaptions.CancelOrder</a>
                                                            }
                                                        }
                                                    </td>
                                                </tr>
                                            }

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            @{
                                var orders = Model.OrderVMs;
                            }
                            <partial name="Shared/PartialViews/_Pagination" model="(orders.Item1.Count,orders.Item2,orders.Item3,orders.Item4)" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles
{
<link href="~/AdminContent/assets/select2/select2.css" rel="stylesheet" type="text/css">
}
@section Scripts{
<script src="~/AdminContent/assets/select2/select2.min.js" type="text/javascript"></script>
<script>
    jQuery(".select2").select2({
        width: '100%'
    });
</script>
}

Server/Areas/Administration/Pages/Shop/Orders/OrderItems.cshtml
@model List<ShopManagement.Application.Contracts.Order.OrderItemViewModel>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                            <div class="row m-t-10">
                                <div class="col-sm-12">
                                    <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
                                        <thead>
                                            <tr role="row">
                                                <th>@DataDictionaries.ProductTitle</th>
                                                <th>@DataDictionaries.Color</th>
                                                <th>@DataDictionaries.Count</th>
                                                <th>@(DataDictionaries.UnitPrice+$"({DataDictionaries.Toman})")</th>
                                                <th>@(DataDictionaries.TotalPrice+$"({DataDictionaries.Toman})")</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr role="row">
                                                    <td>@item.ProductTitle</td>
                                                    <td>@item.ColorName</td>
                                                    <td>@item.Count</td>
                                                    <td>@item.UnitPrice.ToString("#,0")</td>
                                                    <td>@item.TotalPrice.ToString("#,0")</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>