Server/Areas/Administration/Pages/Roles/Create.cshtml.cs
using _01_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using UserManagement.Application.Contracts.Role;

namespace Server.Areas.Administration.Pages.Roles
{
    public class CreateModel : PageModel
    {
        public CreateModel(IRoleApplication roleApplication,IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication=roleApplication;
            _exposers=exposers;
        }
        private readonly IRoleApplication _roleApplication;

        private readonly IEnumerable<IPermissionExposer> _exposers;

        public string ErrorMessage { get; set; }

        [BindProperty]
        public CreateRoleCommand Command { get; set; }

        public List<SelectListItem> Permissions { get; set; } = new List<SelectListItem>();

        public void GetInformations()
        {
            foreach (var exposer in _exposers)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var (key,value) in exposedPermissions)
                {
                    var group = new SelectListGroup() {Name = key};
                    foreach (var permission in value)
                    {
                        Permissions.Add( new SelectListItem(permission.PermissionTitle, permission.PermissionCode.ToString())
                        {
                            Group = group
                        });
                    }
                }
            }
        }

        [NeedsPermission(RolePermissions.CreateRole)]
        public void OnGet()
        {
            GetInformations();
        }

        [NeedsPermission(RolePermissions.CreateRole)]
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
                return RedirectToPage();
            
            var result=_roleApplication.Create(Command);
            if (!result.IsSucceeded)
            {
                ErrorMessage = result.Message;
                GetInformations();
                return Page();
            }
            return RedirectToPage("Index");
        }
    }
}

Server/Areas/Administration/Pages/Roles/Edit.cshtml.cs
using _01_Framework.Application;
using _01_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using UserManagement.Application.Contracts.Role;

namespace Server.Areas.Administration.Pages.Roles
{
    public class EditModel : PageModel
    {
        public EditModel(IRoleApplication roleApplication,IEnumerable<IPermissionExposer> exposers,IAuthenticationHelper authenticationHelper)
        {
            _roleApplication=roleApplication;
            _exposers=exposers;
            _authenticationHelper=authenticationHelper;
        }

        private readonly IEnumerable<IPermissionExposer> _exposers;
        private readonly IAuthenticationHelper _authenticationHelper;
        private readonly IRoleApplication _roleApplication;

        public string ErrorMessage { get; set; }
        [BindProperty]
        public EditRoleCommand Command { get; set; }

        public List<SelectListItem> Permissions { get; set; } = new List<SelectListItem>();

        public void GetInformations()
        {
            foreach (var exposer in _exposers)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var (key,value) in exposedPermissions)
                {
                    var group = new SelectListGroup() {Name = key};
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.PermissionTitle, permission.PermissionCode.ToString())
                        {
                            Group = group
                        };
                        if (Command.PermissionCodes.Any(c=>c==permission.PermissionCode))
                            item.Selected = true;
                        Permissions.Add(item);
                    }
                }
            }
        }

        [NeedsPermission(RolePermissions.EditRole)]
        public void OnGet(long roleId)
        {
            Command = _roleApplication.GetRoleForEdit(roleId);
            GetInformations();
        }
        
        [NeedsPermission(RolePermissions.EditRole)]
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
                return RedirectToPage();
            var result = _roleApplication.Edit(Command);
            if (!result.IsSucceeded)
            {
                ErrorMessage = result.Message;
                GetInformations();
                return Page();
            }
            return RedirectToPage("Index");
        }
    }
}

Server/Areas/Administration/Pages/Shop/Orders/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Order;
using UserManagement.Application.Contracts.User;

namespace Server.Areas.Administration.Pages.Shop.Orders
{
    public class IndexModel : PageModel
    {
        private readonly IOrderApplication _orderApplication;
        private readonly IUserApplication _userApplication;

        public IndexModel(IOrderApplication orderApplication,IUserApplication userApplication)
        {
            _orderApplication = orderApplication;
            _userApplication = userApplication;
        }

        public SelectList UsersSelectList { get; set; }
        public Tuple<List<OrderViewModel>,int,int,int> OrderVMs { get; set; }

        public OrderSearchModel SearchModel { get; set; }
        public void OnGet(OrderSearchModel searchModel)
        {
            ViewData["Take"] = searchModel.Take;
            UsersSelectList = new SelectList(_userApplication.GetUsersForSelect(), "Value", "Text");
            OrderVMs = _orderApplication.GetOrders(searchModel);
        }

        public IActionResult OnGetShowOrderItems(long orderId)
        {
            var orderItems = _orderApplication.GetOrderItems(orderId);
            return Partial("./OrderItems",orderItems);
        }

        public IActionResult OnGetConfirmOrder(long orderId)
        {
            return Partial("./Confirm",orderId);
        }

        public IActionResult OnPostConfirmOrder(long orderId)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _orderApplication.ConfirmOrderForSent(orderId);
            return new JsonResult(result);
        }

        public IActionResult OnGetCancelOrder(long orderId)
        {
            return Partial("./Cancel", orderId);
        }

        public IActionResult OnPostCancelOrder(long orderId)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _orderApplication.CancelOrder(orderId);
            return new JsonResult(result);
        }
    }
}

Server/Areas/Administration/Pages/Shop/ProductBrands/Index.cshtml.cs
using System.Collections.Immutable;
using _01_Framework.Resources;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductBrand;

namespace Server.Areas.Administration.Pages.Shop.ProductBrands
{
    public class IndexModel : PageModel
    {
        private readonly IProductBrandApplication _productBrandApplication;

        public IndexModel(IProductBrandApplication productBrandApplication)
        {
            _productBrandApplication = productBrandApplication;
        }

        public Tuple<List<ProductBrandViewModel>,int,int,int> ProductBrandVms { get; set; }
        public void OnGet(int pageId=1,string title="",int take=20)
        {
            if (take % 20 != 0)
                take = 20;
            ViewData["Take"] = take;
            ProductBrandVms = _productBrandApplication.GetProductBrands(pageId,title,take);
        }

        public IActionResult OnGetCreate()
        {
            return Partial("./Create");
        }

        public IActionResult OnPostCreate(CreateBrandCommand command)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var result = _productBrandApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long brandId)
        {
            var brand = _productBrandApplication.GetBrandForEdit(brandId);
            return Partial("./Edit", brand);
        }

        public IActionResult OnPostEdit(EditBrandCommand command)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productBrandApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetDelete(long brandId)
        {
            if (_productBrandApplication.IsProductsHaveBrand(brandId))
            {
                return BadRequest(ErrorMessages.DeleteBrandErrorMessage);
            }
            var brand= _productBrandApplication.GetBrandForDelete(brandId);
            return Partial("./Delete",brand);
        }

        public IActionResult OnPostDelete(DeleteBrandCommand command)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productBrandApplication.Delete(command);
            return new JsonResult(result);
        }
    }
}

Server/Areas/Administration/Pages/Shop/ProductColors/Index.cshtml.cs
using _01_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductColor;
using ShopManagement.Infrastructure.Configuration.Permissions;

namespace Server.Areas.Administration.Pages.Shop.ProductColors
{
    public class IndexModel : PageModel
    {
        private readonly IProductColorApplication _productColorApplication;

        public IndexModel(IProductColorApplication productColorApplication)
        {
            _productColorApplication = productColorApplication;
        }

        [NeedsPermission(ProductPermissions.CreateProductColor)]
        public IActionResult OnGetCreate(long productId)
        {
            return Partial("./Create",new CreateColorCommand(){ProductId = productId});
        }

        [NeedsPermission(ProductPermissions.CreateProductColor)]
        public IActionResult OnPostCreate(CreateColorCommand command)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productColorApplication.Create(command);
            return new JsonResult(result);
        }

        [NeedsPermission(ProductPermissions.DeleteProductColor)]
        public IActionResult OnPostDelete(long colorId)
        {
            if (!ModelState.IsValid)
                return Redirect("/Administration/Shop/Products");
            _productColorApplication.Delete(colorId);
            return Redirect("/Administration/Shop/Products");
        }
    }
}

Server/Areas/Administration/Pages/Shop/ProductGroups/GroupDetails/Index.cshtml.cs
using _01_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductGroup;
using ShopManagement.Infrastructure.Configuration.Permissions;

namespace Server.Areas.Administration.Pages.Shop.ProductGroups.GroupDetails
{
    public class IndexModel : PageModel
    {
        private readonly IProductGroupApplication _productGroupApplication;

        public IndexModel(IProductGroupApplication productGroupApplication)
        {
            _productGroupApplication = productGroupApplication;
        }

        public List<GroupDetailViewModel> GroupDetailVms { get; set; }
        [BindProperty]
        public CreateGroupDetailCommand command { get; set; }

        [NeedsPermission(ProductGroupPermissions.GroupDetailsList)]
        public void OnGet(long groupId)
        {
            command = new CreateGroupDetailCommand()
            {
                GroupId = groupId
            };
            GroupDetailVms = _productGroupApplication.GetDetailsOfGroup(groupId);
        }

        [NeedsPermission(ProductGroupPermissions.CreateGroupDetail)]
        public IActionResult OnPostCreate()
        {
            ModelState.Remove("DetailId");
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productGroupApplication.CreateGroupDetail(command);
            return new JsonResult(result);
        }

        [NeedsPermission(ProductGroupPermissions.EditGroupDetail)]
        public IActionResult OnPostEdit()
        {
            if (!ModelState.IsValid || command.DetailId==null)
                return BadRequest();
            var result = _productGroupApplication.EditGroupDetail(command);
            return new JsonResult(result);
        }
    }
}

Server/Areas/Administration/Pages/Shop/ProductGroups/Index.cshtml.cs
using _01_Framework.Infrastructure;
using _01_Framework.Resources;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductGroup;
using ShopManagement.Infrastructure.Configuration.Permissions;

namespace Server.Areas.Administration.Pages.Shop.ProductGroups
{
    public class IndexModel : PageModel
    {
        public IndexModel(IProductGroupApplication productGroupApplication,IProductApplication productApplication)
        {
            _productGroupApplication = productGroupApplication;
            _productApplication = productApplication;
        }
        private readonly IProductGroupApplication _productGroupApplication;
        private readonly IProductApplication _productApplication;
        public Tuple<List<ProductGroupViewModel>,int,int,int> ProductGroupVm { get; set; }

        [NeedsPermission(ProductGroupPermissions.PoductGroupsList)]
        public void OnGet(int pageId=1,string title="",int take=10)
        {
            if (take % 10 != 0)
                take = 10;
            ViewData["Take"] = take;
            ProductGroupVm = _productGroupApplication.GetProductGroupsForShow(pageId, title, take);
        }

        [NeedsPermission(ProductGroupPermissions.CreateGroup)]
        public IActionResult OnGetCreate(long? parentId)
        {
            var createGroupCommand = new CreateGroupCommand()
            {
                ParentId = parentId
            };
            return Partial("./Create",createGroupCommand);
        }

        [NeedsPermission(ProductGroupPermissions.CreateGroup)]
        public IActionResult OnPostCreate(CreateGroupCommand command)
        {
            ModelState.Remove("ParentId");
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productGroupApplication.CreateGroup(command);
            return new JsonResult(result);
        }

        [NeedsPermission(ProductGroupPermissions.EditGroup)]
        public IActionResult OnGetEdit(long groupId)
        {
            var group = _productGroupApplication.GetGroupForEdit(groupId);
            return Partial("./Edit",group);
        }

        [NeedsPermission(ProductGroupPermissions.EditGroup)]
        public IActionResult OnPostEdit(EditGroupCommand command)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productGroupApplication.EditGroup(command);
            return new JsonResult(result);
        }

        [NeedsPermission(ProductGroupPermissions.DeleteGroup)]
        public IActionResult OnGetDelete(long groupId)
        {
            if (_productApplication.IsExistProductByGroup(groupId))
            {
                return BadRequest(ErrorMessages.DeleteGroupErrorMessage);
            }

            var group = _productGroupApplication.GetGroupForDelete(groupId);
            return Partial("./Delete",group);
        }

        [NeedsPermission(ProductGroupPermissions.DeleteGroup)]
        public IActionResult OnPostDelete(long groupId)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productGroupApplication.DeleteGroup(groupId);
            return new JsonResult(result);
        }
    }
}

Server/Areas/Administration/Pages/Shop/Products/ProductDetails/Index.cshtml.cs
using _01_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Infrastructure.Configuration.Permissions;

namespace Server.Areas.Administration.Pages.Shop.Products.ProductDetails
{
    public class IndexModel : PageModel
    {
        private readonly IProductApplication _productApplication;

        public IndexModel(IProductApplication productApplication)
        {
            _productApplication = productApplication;
        }

        public List<ProductDetailViewModel> ProductDetailVms { get; set; }

        [NeedsPermission(ProductPermissions.ConfirmProductDetails)]
        public void OnGet(long productId)
        {
            @ViewData["ProductId"] = productId;
            ProductDetailVms = _productApplication.GetProductDetails(productId);
        }

        [NeedsPermission(ProductPermissions.ConfirmProductDetails)]
        public IActionResult OnPost(long productId,Dictionary<int,string> details)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var result = _productApplication.ConfirmProductDetails(productId, details);
            return new JsonResult(result);
        }
    }
}

Server/Areas/Administration/Pages/Shop/ProductBrands/Create.cshtml
@model ShopManagement.Application.Contracts.ProductBrand.CreateBrandCommand
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">@DataDictionaries.CreateNewBrand</h4>
</div>
<form asp-page="./Index"
      asp-page-handler="Create"
      data-ajax="true"
      data-action="Refresh"
      data-callback=""
      enctype="multipart/form-data"
      method="post">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <input asp-for="Title" type="text" class="form-control" placeholder="@DataDictionaries.Title"/>
                    <span asp-validation-for="Title" class="error"></span>
                    <br/>
                    <input asp-for="OtherLangTitle" type="text" class="form-control" placeholder="@DataDictionaries.OtherLangTitle"/>
                    <span asp-validation-for="OtherLangTitle" class="error"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <img id="imgAvatar" src="/Products/BrandImages/ProductBrand.png" class="image img-thumbnail" style="width: 100%; height: 100%"/>
                    <hr/>
                    <input id="imgInp" asp-for="BrandImage" type="file" class="form-control"/>
                    <span asp-validation-for="BrandImage" class="error"></span>
                </div>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-info waves-effect waves-light">@ButtonCaptions.Add</button>
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">@ButtonCaptions.Cancel</button>
    </div>
</form>

<script src="~/assets/js/library/jquery.validate.min.js"></script>
<script src="~/assets/js/library/jquery.validate.unobtrusive.min.js"></script>

<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#imgAvatar').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#imgInp").change(function () {
        readURL(this);
    });
</script>

Server/Areas/Administration/Pages/Shop/ProductBrands/Delete.cshtml
@model ShopManagement.Application.Contracts.ProductBrand.DeleteBrandCommand
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">@DataDictionaries.DeleteBrand</h4>
</div>
<form asp-page="./Index"
      asp-page-handler="Delete"
      data-ajax="true"
      data-action="Refresh"
      enctype="multipart/form-data"
      method="post">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-8">
                <h4>
                    @ConfirmationMessages.DeleteBrandConfirmationS1
                    <span class="error">@Model.BrandTitle</span>
                    @ConfirmationMessages.DeleteBrandConfirmationS2
                </h4>
                <input asp-for="BrandId" type="hidden" />
            </div>
            <div class="col-md-4">
                <img class="image img-thumbnail" src="~/Products/BrandImages/@Model.ImageName" asp-append-version="true"/>
            </div>
        </div>
        
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-info waves-effect waves-light">@ButtonCaptions.Delete</button>
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">@ButtonCaptions.Cancel</button>
    </div>

</form>

Server/Areas/Administration/Pages/Shop/ProductBrands/Edit.cshtml
@model ShopManagement.Application.Contracts.ProductBrand.EditBrandCommand
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">@DataDictionaries.CreateNewBrand</h4>
</div>
<form asp-page="./Index"
      asp-page-handler="Edit"
      data-ajax="true"
      data-action="Refresh"
      data-callback=""
      enctype="multipart/form-data"
      method="post">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <input asp-for="BrandId" type="hidden"/>
                    <input asp-for="ImageName" type="hidden"/>
                    <input asp-for="Title" type="text" class="form-control" placeholder="@DataDictionaries.Title"/>
                    <span asp-validation-for="Title" class="error"></span>
                    <br/>
                    <input asp-for="OtherLangTitle" type="text" class="form-control" placeholder="@DataDictionaries.OtherLangTitle"/>
                    <span asp-validation-for="OtherLangTitle" class="error"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <img id="imgAvatar" src="/Products/BrandImages/@Model.ImageName" class="image img-thumbnail" style="width: 100%; height: 100%"/>
                    <hr/>
                    <input id="imgInp" asp-for="BrandImage" type="file" class="form-control"/>
                    <span asp-validation-for="BrandImage" class="error"></span>
                </div>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-info waves-effect waves-light">@ButtonCaptions.Edit</button>
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">@ButtonCaptions.Cancel</button>
    </div>
</form>

<script src="~/assets/js/library/jquery.validate.min.js"></script>
<script src="~/assets/js/library/jquery.validate.unobtrusive.min.js"></script>

<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#imgAvatar').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#imgInp").change(function () {
        readURL(this);
    });
</script>

Server/Areas/Administration/Pages/Shop/ProductBrands/Index.cshtml
@page "{handler?}"
@model Server.Areas.Administration.Pages.Shop.ProductBrands.IndexModel
@{
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">@DataDictionaries.BrandsList</h3>
            </div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                            <div class="m-b-15">
                                <a id="btnCreateBrand" class="btn btn-info smallModal">@ButtonCaptions.AddNewBrand</a>
                            </div>
                            <form method="get">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div id="datatable_filter" class="dataTables_filter">
                                            <input name="title" type="search" class="form-control input-sm" placeholder="@DataDictionaries.Title" aria-controls="datatable">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="dataTables_length" id="datatable_length">
                                            <select name="take" aria-controls="datatable" class="form-control input-sm">
                                                @for (var i = 1; i <= 4; i++)
                                                {
                                                    int x = 20;
                                                    if (i * x == (int)ViewData["Take"])
                                                    {
                                                        <option value="@(i * x)" selected>@(i * x)</option>
                                                    }
                                                    else
                                                    {
                                                        <option value="@(i*x)">@(i*x)</option>
                                                    }
                                                }
                                            </select>
                                            @DataDictionaries.Record
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div id="datatable_filter" class="dataTables_filter">
                                            <input type="submit" class="btn btn-primary" value="@ButtonCaptions.Search" />
                                            &nbsp;
                                            <a href="/Administration/Shop/ProductBrands" class="btn btn-warning">@ButtonCaptions.Clear</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <div class="row m-t-10">
                                <div class="col-sm-12">
                                    <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
                                        <thead>
                                            <tr role="row">
                                                <th>@DataDictionaries.Image</th>
                                                <th>@DataDictionaries.Title</th>
                                                <th>@DataDictionaries.OtherLangTitle</th>
                                                <th>@DataDictionaries.Operations</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var brand in Model.ProductBrandVms.Item1)
                                            {
                                                <tr role="row">
                                                    <td>
                                                        <img src="/Products/BrandImages/@brand.ImageName" style="width: 80px; height: 80px" class="img-thumbnail">
                                                    </td>
                                                    <td>@brand.BrandTitle</td>
                                                    <td>@brand.OtherLangTitle</td>
                                                    <td>
                                                        <a onclick="GetBrandForEdit(@brand.BrandId)" class="btn btn-primary btn-block smallModal">@ButtonCaptions.Edit</a>
                                                        <a onclick="GetBrandForDelete(@brand.BrandId)" class="btn btn-danger btn-block smallModal">@ButtonCaptions.Delete</a>
                                                    </td>
                                                </tr>
                                            }

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    @{
                                        int take = Model.ProductBrandVms.Item4;
                                        int pageId = Model.ProductBrandVms.Item2;
                                        int totalEntries = Model.ProductBrandVms.Item1.Count();
                                        int startEntry = (pageId - 1) * take;
                                        if (totalEntries != 0)
                                            startEntry += 1;
                                        int endEntry = pageId * take;
                                        if (totalEntries < endEntry)
                                            endEntry = totalEntries;
                                    }
                                    <div class="dataTables_info" id="datatable_info" role="status" aria-live="polite">
                                        @DataDictionaries.Showing @startEntry @DataDictionaries.To @endEntry @DataDictionaries.Of @totalEntries @DataDictionaries.Entries
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="dataTables_paginate paging_simple_numbers" id="datatable_paginate">
                                        <ul class="pagination">
                                            @for (var i = 1; i <= Model.ProductBrandVms.Item3; i++)
                                            {
                                                <li class="paginate_button @((Model.ProductBrandVms.Item2==i)?"active":"")" aria-controls="datatable" tabindex="0"><a href="/Admin/Users?pageId=@i">@i</a></li>
                                            }
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>